cloudstack:
  host:       'coe-preprod2-mgt02.lab.cloudops.local'
  port:       '8080'
  api_key:    'IPACIPotOKxMphvegfgHXWLWjxNF5kbEe8EjdovqLkpJGy4VUnlFlEpjXShkn16vst2a8pevd8eF2DdxOIPO6w'
  secret_key: 'swlXavzGjbKyQxgeptSX_IzYXerjJPx_RYVa0plzlqB41PTCsjS_8ICAlmwz0hgZyRrw6WXVFLFcC2hUDUb9Fg'
